;PROGRAMA QUE MEDIANTE UN SWITCH CONECTADO EN RA4 ENCIENDE LOS BITS PARES DEL PUERTO B CUANDO ESTÁ CERRADO (VALE 1)
;Y ENCIENDE LOS BITS IMPARES DEL MISMO PUERTO CUANDO ESTÁ ABIERTO (VALE 0)
    
    LIST P = 18F4550
    #INCLUDE <p18f4550.inc>
    
    #DEFINE SWITCH PORTA, 4, 0
    #DEFINE PARES B'01010101'
    #DEFINE IMPARES B'10101010'
    
    ORG 0
    
    INICIO
	CLRF	PORTA, 0
	MOVLW	B'00010000'
	MOVWF	TRISA, 0
	MOVLW	.15
	MOVWF	ADCON1, 0
	MOVLW	.7
	MOVWF	CMCON, 0
	CLRF	PORTB, 0
	CLRF	TRISB, 0
	
    MAIN
	BTFSC	SWITCH		    ; SI RA4 = 0 --> SALTA UNA LINEA
	GOTO	ENCENDER_PARES
	GOTO	ENCENDER_IMPARES
	
    ENCENDER_PARES
	MOVLW	PARES		    ; ASIGNO A W LA CONFIGURACIÓN PAR PARA ENCENDER PARES (01010101)
	MOVFF	WREG, PORTB	    ; ASIGNO LA MISMA CONFIGURACIÓN DE BITS AL PUERTO B
	GOTO	MAIN
	
    ENCENDER_IMPARES
	MOVLW	IMPARES		    ; ASIGNO A W LA CONFIGURACIÓN PAR PARA ENCENDER PARES (10101010)
	MOVFF	WREG, PORTB	    ; ASIGNO LA MISMA CONFIGURACIÓN DE BITS AL PUERTO B
	GOTO	MAIN
	
    END