; MULTIPLICAR DOS CANTIDADES DE TRES BITS QUE INGRESAN POR EL PUERTO A Y EL RESULTADO SALE POR EL PUERTO B
    
    LIST P = 18F4550
    #INCLUDE<p18f4550.inc>
    
    #DEFINE N1	    H'10' ; SE ASIGNÓ LA DIRECCIÓN 16 DEL BANCO INDEFINIDO AL REGISTRO N1
    #DEFINE N2	    H'11' ; SE ASIGNÓ LA DIRECCIÓN 17 DEL BANCO INDEFINIDO AL REGISTRO N2
    
    ORG 0
    
; CONFIGURAR SFR's
    CONFIGURAR
	SETF	TRISA,  0    ; TRISA = 1111 1111 POR LO QUE LOS PINES DEL PUERTO A SE CONVIERTEN EN -EEE EEEE (ENTRADAS)
	MOVLW	H'07'	     ; W = 7
	MOVWF	CMCON,  0    ; CMCON = 7 Y EL COMPARADOR DE VOLTAJES UBICADO EN PORTA Y PORTE SE APAGA
	MOVLW	H'0F'	     ; W = 15
	MOVWF	ADCON1, 0    ; ADCON1 = 15 Y LOS PUERTOS A, B Y E DEL PIC SOLO PUEDEN FUNCIONAR COMO ENTRADAS DE TIPO ANALOGICO (EN EL CASO DE SER ENTRADAS)
	CLRF	PORTA,  0    ; PORTA = 0000 0000, ES DECIR QUE EL PUERTO A SE LIMPIA
	CLRF	TRISB,  0    ; TRISB = 0000 0000 POR LO QUE LOS PINES DEL PUERTO B SE CONVIERTEN EN SSSS SSSS (SALIDAS)
	CLRF	PORTB,	0    ; PORTB = 0000 0000
	
    MAIN
	MOVFF	PORTA, N2	; N2 = PORTA
	MOVLW	B'00000111'	; SELECCIONO LA MASCARA QUE VA A TENER N2
	ANDWF	N2, F, 1	; ENMASCARO N2 PARA QUEDARME CON EL SEGUNDO NIBBLE Y EL RESULTADO SE GUARDA EN N2
	MOVFF	PORTA, N1	; N1 = PORTA
	MOVLW	B'00111000'	; SELECCIONO LA MASCARA QUE VA A TENER N1
	ANDWF	N1, F, 1	; ENMASCARO N1 PARA QIEDARME CON EL PRIMER NIBLE Y EL RESULTADO SE GUARDA EN N1
	RRNCF	N1, F, 1	; HAGO LA ROTACIÓN 1
	RRNCF	N1, F, 1	; HAGO LA ROTACIÓN 2
	RRNCF	N1, F, 1	; HAGO LA ROTACIÓN 3
	MOVF	N1, W, 1	; W = N1
	MULWF	N2, 1		; PRODL = W - N2, ES DECIR, SE RESTAN N1 Y N2 Y EL RESULTADO SE GUARDA EN PRODL
	MOVFF	PRODL, PORTB	; PORTB = RESTA
	GOTO	MAIN
	END