;PROGRAMA QUE MEDIANTE DOS SWITCHES CONECTADOS EN RC2 Y RC1 DEFINE QUÉ OPERACIÓN SE HARÁ CON
;LOS NUMEROS DE 3 BITS QUE ENTRAN POR EL PUERTO A Y MOSTRARÁ EL RESULTADO EN EL PUERTO B
    
    LIST P = 18F4550
    #INCLUDE <p18f4550.inc>
    
    #DEFINE N1 H'10'
    #DEFINE N2 H'11'
    #DEFINE SUMA H'12'
    #DEFINE RESTA H'13'
    #DEFINE MULTI H'14'
    #DEFINE RC1 PORTC,1,0
    #DEFINE _RC2 PORTC,2,0
    
    ORG 0
    
    INICIO
	CLRF	PORTA, 0
	MOVLW	B'00111111'
	MOVWF	TRISA, 0
	CLRF	PORTC, 0
	MOVLW	B'00000110'
	MOVWF	TRISC, 0
	MOVLW	.15
	MOVWF	ADCON1, 0
	MOVLW	.7
	MOVWF	CMCON, 0
	CLRF	PORTB, 0
	CLRF	TRISB, 0
	
    MAIN
	MOVFF	PORTA, N2	    ; N2 = PORTA
	MOVLW	B'00000111'	    ; SELECCIONO LA MASCARA QUE VA A TENER N2
	ANDWF	N2, F, 1	    ; ENMASCARO N2 PARA QUEDARME CON EL SEGUNDO NIBBLE Y EL RESULTADO SE GUARDA EN N2
	MOVFF	PORTA, N1	    ; N1 = PORTA
	MOVLW	B'00111000'	    ; SELECCIONO LA MASCARA QUE VA A TENER N1
	ANDWF	N1, F, 1	    ; ENMASCARO N1 PARA QIEDARME CON EL PRIMER NIBLE Y EL RESULTADO SE GUARDA EN N1
	RRNCF	N1, F, 1	    ; HAGO LA ROTACIÓN 1
	RRNCF	N1, F, 1	    ; HAGO LA ROTACIÓN 2
	RRNCF	N1, F, 1	    ; HAGO LA ROTACIÓN 3
	BTFSC	_RC2		    ; SI RC2 = 0 --> SALTA UNA LINEA
	GOTO	VERIFICAR_RC1_CON_RC2_EN_UNO
	GOTO	VERIFICAR_RC1_CON_RC2_EN_CERO
	
    VERIFICAR_RC1_CON_RC2_EN_CERO
	BTFSC	RC1		    ; SI RA2 = 0 --> SALTA UNA LINEA
	GOTO	HACER_SUMA
	GOTO	HACER_NADA
	
    VERIFICAR_RC1_CON_RC2_EN_UNO
	BTFSC	RC1		    ; SI RA2 = 0 --> SALTA UNA LINEA
	GOTO	HACER_MULTIPLICACION
	GOTO	HACER_RESTA	
	
    HACER_SUMA
	MOVF	N1, W, 1	; W = N1
	ADDWF	N2, W, 1	; W = W + N2, ES DECIR, SE SUMAN N1 Y N2 Y EL RESULTADO SE GUARDA EN W
	MOVWF	SUMA, 1		; SUMA = W	
	MOVFF	SUMA, PORTB	; PORTB = SUMA
	GOTO	MAIN
	
    HACER_RESTA
	MOVF	N2, W, 1	; W = N1
	SUBWF	N1, W, 1	; W = W - N2, ES DECIR, SE RESTAN N1 Y N2 Y EL RESULTADO SE GUARDA EN W
	MOVWF	RESTA, 1	; RESTA = W	
	MOVFF	RESTA, PORTB	; PORTB = RESTA
	GOTO	MAIN
	
    HACER_MULTIPLICACION
	MOVF	N1, W, 1	; W = N1
	MULWF	N2, 1		; PRODL = W - N2, ES DECIR, SE RESTAN N1 Y N2 Y EL RESULTADO SE GUARDA EN PRODL
	MOVFF	PRODL, PORTB	; PORTB = RESTA
	GOTO	MAIN
	
    HACER_NADA
	CLRF	PORTB, 0
	GOTO	MAIN
	
    END