; MULTIPLICAR UNA CANTIDAD DE DOS BITS QUE INGRESA POR EL PUERTO A (RA2, RA1) * 7 Y EL RESULTADO SALE POR EL PUERTO B
    
    LIST P = 18F4550
    #INCLUDE<p18f4550.inc>
    
    #DEFINE COPIA H'10' ; SE ASIGNÓ LA DIRECCIÓN 16 DEL BANCO INDEFINIDO AL REGISTRO COPIA
    
    ORG 0
    
; CONFIGURAR SFR's
    CONFIGURAR
	SETF	TRISA,  0    ; TRISA = 1111 1111 POR LO QUE LOS PINES DEL PUERTO A SE CONVIERTEN EN -EEE EEEE (ENTRADAS)
	MOVLW	H'07'	     ; W = 7
	MOVWF	CMCON,  0    ; CMCON = 7 Y EL COMPARADOR DE VOLTAJES UBICADO EN PORTA Y PORTE SE APAGA
	MOVLW	H'0F'	     ; W = 15
	MOVWF	ADCON1, 0    ; ADCON1 = 15 Y LOS PUERTOS A, B Y E DEL PIC SOLO PUEDEN FUNCIONAR COMO ENTRADAS DE TIPO ANALOGICO (EN EL CASO DE SER ENTRADAS)
	CLRF	PORTA,  0    ; PORTA = 0000 0000, ES DECIR QUE EL PUERTO A SE LIMPIA
	CLRF	TRISB,  0    ; TRISB = 0000 0000 POR LO QUE LOS PINES DEL PUERTO B SE CONVIERTEN EN SSSS SSSS (SALIDAS)
	CLRF	PORTB,	0    ; PORTB = 0000 0000
	
    MAIN
	MOVFF	PORTA, COPIA    ; COPIA = PORTA QUE PUEDEN SER NUMEROS DE 2 BITS (0, 1, 2, 3)
	MOVLW	B'00000110'	; W TENDRÁ LA MASCARA (0000 0110) PARA CONSERVAR A RA1 Y RA2
	ANDWF	COPIA, 1, 1	; SE "MULTIPLICA" COPIA CON LA MASCARA (CONTENIDA EN W) PARA ENMASCARAR A LA COPIA
	RRNCF	COPIA, 1, 1	; SE ROTA A LA IZQUIERZA A COPIA PARA TENER EL DATO COMO SI SE HUBIERA INGRESADO DESDE RA0
	MOVLW	H'07'		; W = 7
	MULWF	COPIA, 1	; SE MULTIPLICA COPIA POR 7. SE PUEDEN TENER RESULTADOS COMO 0, 7, 14, 21
	MOVFF	PRODL, PORTB	; PORTB SE IGUALA CON PRODL (EL RESULTADO DE LA MULTIPLICACIÓN PARA MOSTRARLO COMO SALIDA)
	GOTO	MAIN
	END