;PROGRAMA DE LED CONECTADO EN RC0 QUE ENCIENDE SI EL SWITCH CONECTADO EN RA3 ESTÁ CERRADO (VALE 1)
    
    LIST P = 18F4550
    #INCLUDE<p18f4550.inc>
    
    #DEFINE SWITCH PORTA, 3, 0	; SE DEFINE SWITCH COMO EL BIT 3 DEL PUERTO A
    #DEFINE LED PORTC, 0, 0	; SE DEFINE LED COMO EL BIT 0 DEL PUERTO C
    
    ORG 0
    
    INICIO
	CLRF	PORTA, 0
	MOVLW	B'00001000'
	MOVWF	TRISA, 0
	MOVLW	.15
	MOVWF	ADCON1, 0
	MOVLW	.7
	MOVWF	CMCON, 0
	CLRF	PORTC, 0
	CLRF	TRISC, 0

    MAIN
	BTFSC	SWITCH	; SI RA3 = 0 --> SALTA UNA LINEA
	GOTO	ENCENDER
	GOTO	APAGAR
	
    APAGAR
	BCF	LED	; RA3 ESTÁ ABIERTO, POR LO QUE EL LED DEBE APAGARSE 
	GOTO	MAIN

    ENCENDER
	BSF	LED	; RA3 ESTÁ CERRADO, POR LO QUE EL LED DEBE ENCENDERSE
	GOTO	MAIN
	END